version: "3.8"

services:
  system-test:
    build:
      context: ..
      dockerfile: system-test/Dockerfile
    ports:
      - "8088:8088"
      - "9093:9093"
      - "6379:6379"
      - "9090:9090"
    environment:
      - PYTHONPATH=/app/src
      - PROMETHEUS_MULTIPROC_DIR=/tmp/prometheus_multiproc
    volumes:
      - ../:/app
    command: /start_test.sh
    container_name: gunicorn-prometheus-test
    restart: "no"
