apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: debug-daemonset
  labels:
    app: debug-test
spec:
  selector:
    matchLabels:
      app: debug-test
  template:
    metadata:
      labels:
        app: debug-test
    spec:
      initContainers:
        - name: wait-for-redis
          image: redis:7-alpine
          command:
            [
              "sh",
              "-c",
              'until redis-cli -h redis-service ping; do echo "Waiting for Redis..."; sleep 2; done',
            ]
      containers:
        - name: debug
          image: redis:7-alpine
          command: ["sleep", "3600"]
