name: Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      placeholder: |
        - OS: [e.g., Ubuntu 20.04, macOS 12.0, Windows 10]
        - Python version: [e.g., 3.9.7]
        - Gunicorn version: [e.g., 20.1.0]
        - gunicorn-prometheus-exporter version: [e.g., 0.1.5]
        - Worker type: [e.g., sync, threads, eventlet, gevent]
        - Redis version: [e.g., 6.2.7] (if using Redis backend)
    validations:
      required: true

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: Your Gunicorn configuration (remove sensitive information)
      placeholder: |
        ```python
        # Your gunicorn configuration
        bind = "0.0.0.0:8000"
        workers = 4
        worker_class = "sync"
        # ... other settings
        ```

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Relevant log output (remove sensitive information)
      placeholder: |
        ```
        Paste your logs here
        ```

  - type: checkboxes
    id: components
    attributes:
      label: Components
      description: Which components are affected by this bug?
      options:
        - label: Hooks
          required: false
        - label: Plugin
          required: false
        - label: Metrics
          required: false
        - label: Master Process
          required: false
        - label: Redis Backend
          required: false
        - label: Configuration Manager
          required: false
        - label: Utils
          required: false
        - label: Multiple Components
          required: false
        - label: Not Applicable
          required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all the requested information
          required: true
        - label: I have tested with the latest version
          required: true
