global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Gunicorn Prometheus Exporter Sidecar
  - job_name: "gunicorn-sidecar"
    static_configs:
      - targets: ["sidecar:9091"]
    scrape_interval: 10s
    metrics_path: "/metrics"
    honor_labels: true

  # Sample application (if it exposes metrics)
  - job_name: "gunicorn-app"
    static_configs:
      - targets: ["app:8000"]
    scrape_interval: 30s
    metrics_path: "/metrics"
    honor_labels: true
