name: Build and Push Docker Images

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  REGISTRY: docker.io
  IMAGE_NAME: princekrroshan01/gunicorn-prometheus-exporter

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # No Docker Hub login needed for build-only workflow

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch,prefix=dev-
            type=sha,prefix=sha-

      - name: Build sidecar image (test only)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Prepare app image tag
        id: app_tag
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            ref='${{ github.head_ref }}'
          else
            ref='${{ github.ref_name }}'
          fi
          sanitized="${ref//\//-}"
          echo "tag=$sanitized" >> "$GITHUB_OUTPUT"

      - name: Build app image (test only)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.app
          platforms: linux/amd64,linux/arm64
          push: false
          tags: |
            ${{ env.REGISTRY }}/princekrroshan01/gunicorn-app:${{ steps.app_tag.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
