name: Build and Verify Docker Containers

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  REGISTRY: docker.io
  IMAGE_NAME: princekrroshan01/gunicorn-prometheus-exporter

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # No Docker Hub login needed for build-only workflow

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch,prefix=dev-
            type=sha,prefix=sha-

      - name: Build sidecar image (test only)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify sidecar image
        run: |
          echo "Verifying sidecar image was built successfully..."
          docker buildx build --load --file ./Dockerfile --platform linux/amd64 --tag verify-sidecar:test .
          if ! docker image inspect verify-sidecar:test > /dev/null 2>&1; then
            echo "::error::Sidecar image not found after build"
            exit 1
          fi
          echo "Sidecar image verification completed successfully"

      - name: Prepare app image tag
        id: app_tag
        env:
          HEAD_REF: ${{ github.head_ref }}
          REF_NAME: ${{ github.ref_name }}
          EVENT_NAME: ${{ github.event_name }}
        run: |
          if [ "$EVENT_NAME" = "pull_request" ]; then
            ref="$HEAD_REF"
          else
            ref="$REF_NAME"
          fi
          sanitized="${ref//\//-}"
          echo "tag=$sanitized" >> "$GITHUB_OUTPUT"

      - name: Build app image (test only)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.app
          platforms: linux/amd64,linux/arm64
          push: false
          tags: |
            ${{ env.REGISTRY }}/princekrroshan01/gunicorn-app:${{ steps.app_tag.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify app image
        run: |
          echo "Verifying app image was built successfully..."
          docker buildx build --load --file ./docker/Dockerfile.app --platform linux/amd64 --tag verify-app:test .
          if ! docker image inspect verify-app:test > /dev/null 2>&1; then
            echo "::error::App image not found after build"
            exit 1
          fi
          echo "App image verification completed successfully"

      - name: Build verification summary
        run: |
          echo "=== Docker Build Verification Summary ==="
          echo "Sidecar image:"
          docker image inspect verify-sidecar:test > /dev/null 2>&1 \
            && echo "verify-sidecar:test present" \
            || echo "Sidecar image not found"
          echo "App image:"
          docker image inspect verify-app:test > /dev/null 2>&1 \
            && echo "verify-app:test present" \
            || echo "App image not found"
          echo "=== All Docker containers built and verified successfully ==="
