name: Integration Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  redis-integration-test:
    runs-on: ubuntu-latest
    name: Redis Integration Test (Ubuntu)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v3

      - name: Run Redis Integration Test (Docker)
        run: |
          cd e2e
          chmod +x ../integration/test_redis_integ.sh
          # Build Docker image for Redis integration test
          docker build -f fixtures/dockerfiles/default.Dockerfile -t gunicorn-prometheus-exporter-test ..
          # Run with proper resource limits
          docker run --rm \
            --name gunicorn-prometheus-test \
            --memory=1g \
            --cpus=2 \
            -p 8088:8088 \
            -p 9093:9093 \
            -p 6379:6379 \
            gunicorn-prometheus-exporter-test
        timeout-minutes: 10

      - name: Upload Redis test artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: redis-integration-logs-ubuntu
          path: |
            *.log
          retention-days: 7

  basic-integration-test:
    runs-on: ubuntu-latest
    name: Basic Integration Test (Ubuntu)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v3

      - name: Run Basic Integration Test (Docker)
        run: |
          cd e2e
          chmod +x ../integration/test_basic.sh
          # Build Docker image for basic file-based integration test
          docker build -f fixtures/dockerfiles/basic.Dockerfile -t gunicorn-prometheus-exporter-basic-test ..
          # Run with proper resource limits
          docker run --rm \
            --name gunicorn-prometheus-basic-test \
            --memory=1g \
            --cpus=2 \
            -p 8088:8088 \
            -p 9093:9093 \
            gunicorn-prometheus-exporter-basic-test
        timeout-minutes: 10

      - name: Upload Basic test artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: basic-integration-logs-ubuntu
          path: |
            *.log
          retention-days: 7

  yaml-integration-test:
    runs-on: ubuntu-latest
    name: YAML Configuration Integration Test (Ubuntu)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v3

      - name: Run YAML Configuration Integration Test (Docker)
        run: |
          cd e2e
          chmod +x ../integration/test_yaml_config.sh
          # Build Docker image for YAML configuration integration test
          docker build -f fixtures/dockerfiles/yaml-simple.Dockerfile -t gunicorn-prometheus-exporter-yaml-test ..
          # Run YAML configuration integration tests
          ../integration/test_yaml_config.sh --docker --quick
        timeout-minutes: 15

      - name: Upload YAML test artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: yaml-integration-logs-ubuntu
          path: |
            *.log
          retention-days: 7
