name: System Tests - Redis Integration & Basic File-based (Linux Docker)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  system-test-redis:
    runs-on: ubuntu-latest
    name: Redis Integration System Test (Ubuntu)
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-docker-action@v3

    - name: Run Redis Integration Docker system test
      run: |
        cd system-test
        chmod +x system_test_redis_integ.sh
        # Build Docker image for Redis integration test
        docker build -f Dockerfile -t gunicorn-prometheus-exporter-test ..
        # Run with proper resource limits
        docker run --rm \
          --name gunicorn-prometheus-test \
          --memory=1g \
          --cpus=2 \
          -p 8088:8088 \
          -p 9093:9093 \
          -p 6379:6379 \
          gunicorn-prometheus-exporter-test
      timeout-minutes: 10

    - name: Upload Redis test artifacts
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: redis-test-logs-ubuntu
        path: |
          *.log
        retention-days: 7

  system-test-basic:
    runs-on: ubuntu-latest
    name: Basic File-based System Test (Ubuntu)
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-docker-action@v3

    - name: Run Basic File-based Docker system test
      run: |
        cd system-test
        chmod +x system_test_basic.sh
        # Build Docker image for basic file-based test
        docker build -f Dockerfile.basic -t gunicorn-prometheus-exporter-basic-test ..
        # Run with proper resource limits
        docker run --rm \
          --name gunicorn-prometheus-basic-test \
          --memory=1g \
          --cpus=2 \
          -p 8088:8088 \
          -p 9093:9093 \
          gunicorn-prometheus-exporter-basic-test
      timeout-minutes: 10

    - name: Upload Basic test artifacts
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: basic-test-logs-ubuntu
        path: |
          *.log
        retention-days: 7
